FROM node:12-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "start"]

# docker build -f Dockerfile.dev .
# docker run -it --name learn-docker-complex-react -p 3000:3000 -v /app/node_modules -v $(pwd):/app <Image ID>