# Travis for /react-cicd app
sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t michael4195/learn-docker-react-cicd -f ./react-cicd/Dockerfile.dev ./react-cicd

script:
  - docker run -e CI=true michael4195/learn-docker-react-cicd npm run test -- --coverage