# Version of docker compose
version: '3'
# A "service" is a type of container
services:
  # * This name should be same as the "host" under "redis.createClient" in index.js
  redis-server:
    # Use a community built image
    image: 'redis'
  node-app:
    # Restart policy
    
    # For 'on-failure' case,
    # the status code passed into 'process.exit' in node app
    # has to be > 0 in order to restart,

    # For 'no' case, it has to be wrapped with quotes because "no"
    # is a reserved keyword in yaml file (mearning false).
    restart: 'always'
    # At the working directory,
    # Look for a Dockerfile and build an image with it
    build: .
    ports:
      # "-" prefix is required in a yaml file for an item of an array
      - '4001:8081'