version: '3'
services:
  web:
    container_name: learn-docker-k8s-react-cicd
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    environment:
      # Specify PORT for react-scripts
      PORT: '4000'
    volumes:
      # DON'T map node_modules,
      # Use the one installed on docker build phrase
      - /app/node_modules
      # Map CWD to /app inside container
      - .:/app
  # For running test script
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]