FROM node:12-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "dev"]

# docker build -f Dockerfile.dev .
# docker run -it --name learn-docker-complex-server -p 5000:5000 -v /app/node_modules -v $(pwd):/app <Image ID>