apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      # Key-value pair that's up to you, like:
      # partOfApp: api
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: stephengrider/multi-server
          ports:
            # "5000" is hardcoded in the ExpressJS app
            - containerPort: 5000
          # Environment variables
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
            # Must be string
              value: '6379'
            - name: PGHOST
              value: redis-cluster-ip-service
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              # Must be string
              value: '5432'
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              # * Get value from secret
              valueFrom: 
                secretKeyRef:
                  name: learn-k8s-pgpassword
                  # There can be more than one pair of key-value pairs in a secret.
                  key: PGPASSWORD