version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
      
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # Meaning: Don't try to overwrite app/node_modules
      - /app/node_modules
      - ./server:/app
    environment:
      # Specify just "- REDIS_HOST" to take value from your computer
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PGPORT: 5432

  client:
    # Otherwise, you will get a "React App exited with Code 0" error in your terminal when we attempt to start up the application.
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      # Meaning: Don't try to overwrite app/node_modules
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      # Meaning: Don't try to overwrite app/node_modules
      - /app/node_modules
      - ./worker:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
